services:
  - type: redis
    name: supplier-server-redis
    plan: starter
    ipAllowList: []
  
  - type: web
    name: supplier-server-web
    env: node
    buildCommand: "yarn"
    startCommand: "yarn server"
    envVars:
      - key: REDIS_URL
        fromService:
          name: supplier-server-redis
          type: redis
          property: connectionString
      - key: WEB_UI_PASSWORD
        sync: false
  
  - type: worker
    name: supplier-server-worker
    env: node
    buildCommand: "yarn"
    startCommand: "yarn worker"
    envVars:
      - key: REDIS_URL
        fromService:
          name: supplier-server-redis
          type: redis
          property: connectionString
      - key: SUPPLIER_STX_KEY
        sync: false
      - key: SUPPLIER_BTC_KEY
        sync: false
      - key: SUPPLIER_ID
        sync: false
      - key: SUPPLIER_NETWORK
        sync: false